#!/bin/bash

docker run -d --hostname demo.k1d-dockerh-01.ksg.int -l traefik.enable=true -l traefik.frontend.rule=Host:demo.k1d-dockerh-01.ksg.int -l traefik.docker.network=traefik_proxy -l treafik.frontend.entryPoints=http,https -l traefik.port=80 --network internal --network traefik_proxy --name demo_1 continuous-demo

docker run -d --hostname demo.k1d-dockerh-01.ksg.int -l traefik.enable=true -l traefik.frontend.rule=Host:demo.k1d-dockerh-01.ksg.int -l traefik.docker-network=traefik_proxy -l traefik.frontend.entryPoints=http,https -l traefik.port=80 --network internal --network traefik_proxy --name demo_2 continuous-demo