package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.buildSteps.dockerCommand
import jetbrains.buildServer.configs.kotlin.v2018_1.buildSteps.exec
import jetbrains.buildServer.configs.kotlin.v2018_1.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Default'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Default")) {
    expectSteps {
        dockerCommand {
            name = "Build docker image"
            commandType = build {
                source = path {
                    path = "dockerfile"
                }
                namesAndTags = "continuous-demo"
            }
        }
        script {
            name = "Run images"
            scriptContent = "./deploy"
        }
    }
    steps {
        insert(1) {
            exec {
                name = "Run images"
                path = "./deploy"
            }
        }
        items.removeAt(2)
    }
}
